server:
    port: 8080
    servlet:
        context-path: /tasks

spring:
    application:
        name: tasks
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tasks}
        username: ${SPRING_DATASOURCE_USERNAME:user}
        password: ${SPRING_DATASOURCE_PASSWORD:password}
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update